sudo: required

branches:
  only:
  - master

services:
  - docker

before_install:
  - docker build -t davidsantander/vue-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true davidsantander/vue-test npm test

after_success:
  - docker build -t davidsantander/multi-frontend ./frontend
  - docker build -t davidsantander/multi-nginx ./nginx
  - docker build -t davidsantander/multi-backend ./backend
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push davidsantander/multi-frontend
  - docker push davidsantander/multi-nginx
  - docker push davidsantander/multi-backend

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: finance
  env: Finance-env
  bucket_name: elasticbeanstalk-us-east-2-452495906375
  bucket_path: docker-multi
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY