version: "3.1"

services:
  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - ./postgresql:/var/lib/postgresql/
    ports:
        - "5432:5432"
  
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - DATABASE_USER=dev
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=finance_db
      - DATABASE_PASSWORD=F1N4nC3
  
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  

