version: "3.1"

services:
  finance-db:
    container_name: "finance-db-container"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
